---  
title: "scRNA-seq: Pre-processing Report"
author: "SysBioLab"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    fig_width: 12
---

<!-- Sergio Alías, 20230606 -->
<!-- Last modified 20230628 -->

<style type='text/css'>
    body .main-container {
        max-width: 90%;

    }

    .plot_real_size {
      overflow: scroll;
      max-height: 600px;
    }

    .plot_real_size img{
      max-width: none;
      max-height: none;
    }

    embed {
   
  }   
</style>

<style>
.dropdown-content {
  display: none;
}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>

# `r name` of project `r experiment`

```{r qc_setup, echo = FALSE}

if (is.null(all_seu)){
  seu <- readRDS(file.path(main_folder,
                           name,
                           "preprocessing.R_0000",
                           paste0(experiment,
                                  ".",
                                  name,
                                  ".seu.RDS")))
} else {
  seu <- all_seu
}
```


```{r child="qc.Rmd"}
```